version: "3.9"

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: openwebui
    ports:
      - "6456:8080"
    volumes:
      - /DATA/AppData/openwebui:/app/backend/data
    environment:
      - OLLAMA_API_BASE=http://192.168.86.30:11434
    restart: unless-stopped
