services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - 3241:3000
    volumes:
      - /DATA/AppData/Homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=192.168.86.248:3241
      - PUID=1000
      - PGID=1000
