services:
  kula:
    stdin_open: true
    tty: true
    container_name: kula
    pid: host
    network_mode: host
    restart: unless-stopped
    ports:
      - 27960:27960
    volumes:
      - /proc:/proc:ro
      - /data:/app/data
    image: c0m4r/kula:latest
networks: {}
